### ISSUE TITLE
mods i suggest to remove

### ISSUE THREAD

**Issue by Kasreti** [AppleMangoOrange/SitakuPack#21]
advanced shulkers (nah)
remove betterf3 from client, make it optional
carry on (im in favour of using leads)
cosm armour (dont think its necessary)
fastleafdecay (i feel like itll cause some issues)
goblin traders (not a fan)
immersive? (neutral but seems like yall dont want)
minecolonies+blockui (we discused this)
journeymap? (atlas sounds cool ig)
multipiston (unnecessary)
refined storage and addons (again, i think unneeded. chests are good enough, ssn if you really needed it)
selectable painting (unnecessary)
structurize (minecoloines shit)
torchmaster (i think its a bit opopipopipopipo id rather use torches, but up to yall)

**Comment by AppleMangoOrange** [comment]
Advanced Shulkers: will be removed
BetterF3: can be disabled by default
Carry-on: It's not only for animals, besides it is used a lot. We have to discuss this
Cosmetic Armour: refer to #17 
FastLeafDecay: Used everywhere, has not caused issue anywhere and even in playtesting
Goblin Traders: will be removed
immersive: refer to #17 
minecolonies: refer to #17 
blockui: refer to #17 
journeymap: now to be replaced by AntiqueAtlas
Multipiston: refer to #17 
refined storage: refer to #17 
selectable painting: it was added after discussion and joint approval
structurize: refer to #17 
torchmaster: will be removed, doesn't work properly anyways. suggest adding anti-griefing method for creepers.
