### ISSUE TITLE
[MOD] Decorative Blocks

### ISSUE THREAD

**Issue by Squiddum** [AppleMangoOrange/SitakuPack#27]
**Name of and link to the mod (from curseforge)**
Use this format to suggest mods:
- [Decorative Blocks](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)

**Short description of the mod**
Adds a variety of decorative blocks (as per namesake). This includes seats, trapdoor variants and multiple lighting blocks. 

**Why should this mod be added to the modpack?**
We do need 1 or 2 mods dedicated to decoration, and I think this one provides enough items to fulfill most decorative needs. 

**Additional context**

**Comment by AppleMangoOrange** [comment]
This mod is already in the modpack.
