### ISSUE TITLE
[MOD] Supplementaries

### ISSUE THREAD

**Issue by Squiddum** [AppleMangoOrange/SitakuPack#29]
**Name of and link to the mod (from curseforge)**
Use this format to suggest mods:
- [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)

**Short description of the mod**
Main feature is adding a crap ton of decorative blocks. Some of these new blocks and items also have neat side functionality (eg cages can be used to capture small mobs). 

**Why should this mod be added to the modpack?**
Many of the decoration blocks we had in 7s came from this mod (eg signs, wall lanterns), so I think this mod is also worth considering alongside other decorative mods

**Additional context**
this mod is the one that let us make the cum jar

**Comment by AppleMangoOrange** [comment]
This mod is already in the modpack
