### ISSUE TITLE
[CONFIG] Reduce spawning of modded stones

### ISSUE THREAD

**Issue by Squiddum** [AppleMangoOrange/SitakuPack#34]
**Name of and link to the mod to change config of (from curseforge)**
Quark (and maybe Create) 

**Config file(s) to change**
Changes to generation of overworld modded stones. I propose to reduce the blob sizes that the stone variants generate in, so they appear a bit more sparsely in the overworld. 
Quark: quark-common.toml
Create: create-common.toml

**Why should this mod be added to the modpack?**
This is based on past experience of us struggling to find vanilla stone due to majority of terrain being replaced by modded stones, locking away many early game recipes that require cobblestone. I remember Quark being the worst offender, with modded stone blobs spanning entire biomes.

**Comment by AppleMangoOrange** [comment]
Alternatively, modded stones could be given the same functionality as regular stone.

**Comment by DrEksplosive** [comment]
An excellent alternative to this is to completely disable quark stones generation, and provide an alternative method to acquire them (stonecutting). Create stones often are required in the mod, and it would make more sense to prioritise those over quark.

**Comment by AppleMangoOrange** [comment]
> An excellent alternative to this is to completely disable quark stones generation, and provide an alternative method to acquire them (stonecutting). Create stones often are required in the mod, and it would make more sense to prioritise those over quark.

It is a good idea, however for the alternative method for acquiring them to make sense, it would have to be locked behind late-early-game. This does seem like a good idea, so I'll make a separate voting for this to see if it is ok with others.

**Comment by Squiddum** [comment]
marked approved since ppl agree we need less modded stones. now to decide what to actually do with the stones

when i have time i'll play around with configs to alter generation and test out some crafting recipes

**Comment by AppleMangoOrange** [comment]
Voting conclusion:
Disable modded stones' generation and make them acquirable using other methods (crafting, stonecutting, create mod)

**Comment by Squiddum** [comment]
ok turns out the modded stones dont generate nearly as often as before, so this change will be held back for now
