### ISSUE TITLE
[MOD] Brutal Bosses

### ISSUE THREAD

**Issue by AppleMangoOrange** [AppleMangoOrange/SitakuPack#35]
**Name of and link to the mod (from curseforge)**
[Brutal Bosses](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)

**Short description of the mod**
Highly customisable mod that doesn't add any entities to the game, rather it makes bosses out of vanilla mobs.

**Why should this mod be added to the modpack?**
Adds a sense of accomplishment to finding loot.

**Additional context**
The bosses can be made weaker initially if necessary, and can also be made harder the more players progress.

**Comment by Squiddum** [comment]
taking a quick peek at the mod, the bosses spawn at loot chests of most structures, so exploring structures early game will be much harder. 

if ppl don't like that, i can look into restricting their spawning within a radius around spawn or something similar
