### ISSUE TITLE
[REMOVAL] Selectable Painting

### ISSUE THREAD

**Issue by AppleMangoOrange** [AppleMangoOrange/SitakuPack#47]
**Which mods do you want removed?**
Selectable Painting
Allows players to select a painting when placing

**Why should these mods be removed?**
Paintings ++ already has this feature.

**Additional context**
-

**Comment by DrEksplosive** [comment]
Fine by me, there's no reason to keep an obsolete mod in the pack, close it then?

**Comment by MCstarVK** [comment]
lol

**Comment by AppleMangoOrange** [comment]
It was closed by @Kasreti by mistake a while ago. Issues will be closed when it is decided that either they won't be implemented, or when the changes are actually made in the pack.
I made the change yesterday, so I'll close this
